ipcutil: fix compilation warning
drivers/platform/x86/intel_scu_ipcutil.c:1832:12: error:
'intel_scu_ipc_read_oemnib' defined but not used [-Werror=unused-function]

Port from fugu: https://android.intel.com/216932

Change-Id: I729c3fa0de9e29c99cf6f606a33700877a0b1041
Tracked-On: https://jira.ndg.intel.com/browse/MARVIN-578
Signed-off-by: Olivier Fourdan <olivier.fourdan@intel.com>
Signed-off-by: Victor Tasayco Loarte <victorx.tasayco.loarte@intel.com>
Orig-Change-Id: I5c6f592a6c80fd8a45c8ae3e887291e9cdd664ed
Reviewed-on: https://android.intel.com/408538
Reviewed-by: Ranquet, GuillaumeX <guillaumex.ranquet@intel.com>
Reviewed-by: Pujol, Benjamin <benjamin.pujol@intel.com>
Reviewed-by: Maalem, Saadi <saadi.maalem@intel.com>